### ISSUE TITLE
genotype error

### ISSUE THREAD

**Issue by RaSieb** [iqbal-lab/Mykrobe-predictor#104] opened 2016-05-13 23:17 UTC
Hey, 
I am trying to set up _genotype_ with your example data, but keep on getting this error:

[14 May 2016 00:48:13-MUD][memory] We made 20 allocs
[14 May 2016 00:48:13-MUD] Done.
[14 May 2016 00:48:13-MUD][time] 14.00 seconds
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/mykrobe", line 9, in <module>
    load_entry_point('mykrobe==0.3.3', 'console_scripts', 'mykrobe')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mykrobe/mykrobe_predictor.py", line 98, in main
    args.func(parser, args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mykrobe/mykrobe_predictor.py", line 31, in run_subtool
    run(parser, args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mykatlas/cmds/genotype.py", line 51, in run
    print(json.dumps(run_main(parser, args), indent=4))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/mykatlas/cmds/genotype.py", line 42, in run_main
    variant_confidence_threshold=args.min_variant_conf,
AttributeError: 'Namespace' object has no attribute 'min_variant_conf'

My input string is:
`mykrobe genotype asada example-data/staph-amr-bradley_2015.fasta -1 /seqs/a_S30_L001_R1_001.fastq.gz /seqs/a_S30_L001_R2_001.fastq.gz`

The sequences run fine in _predict_ with the latest version installed.

Thanks in advance for any advise!

**Comment by Phelimb** [comment] 2016-05-16 09:27
Thanks! 

This was caused by an update in the API of an underlying library. This should be fixed in 9d196c7230e8a4bf34ffb821bfbc826726246245. 

To update run:

`pip install mykrobe --upgrade`

**Comment by Phelimb** [comment] 2016-05-16 09:28
`mykrobe --version`

should return 

`mykrobe v0.3.6*`

**Closed by Phelimb** 2016-05-16 09:27 UTC

**Comment by RaSieb** [comment] 2016-05-17 12:59
Yeps, thanks a lot!
It works perfectly now.
